### ISSUE TITLE
Implement Project Details Full-Page Navigation

### ISSUE THREAD

**Issue by shiftsave** [shiftsave/anni-platform#36]
This PR implements a full-page control structure and controls to add, remove and sort the sections of a project.

#### Prototype
![projectdetalsnav](https://user-images.githubusercontent.com/1121873/27059824-81ab5be8-4f8d-11e7-8ac8-7ed345424493.gif)

#### To-Do
- [ ] Add sections to project
- [ ] Remove sections from project
- [ ] Sort sections
- [ ] Persist order of sections in database
- [x] Persist content within the sections in database
- [x] Style controls (see below)

**Comment by shiftsave** [comment]
@hudakdidit we need to add the functionality for adding sections and sorting.
